networks:
  network1:
    name: network1

services:
  nginx1:
    container_name: nginx1
    image: nginx
    ports:
      - "80:80"
    volumes:
      - .\docker\nginx\vhost.conf:/etc/nginx/conf.d/default.conf
      - .\public:/var/www/html/public
    networks:
      - network1
    depends_on:
      - php1
      - mysql1
  php1:
    container_name: php1
    build: .\docker\php
    volumes:
      - .:/var/www/html
    ports:
        - "5173:5173"
    networks:
      - network1
    depends_on:
      - mysql1
  mysql1:
    container_name: mysql1
    image: mysql
    volumes:
      - .\docker\mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - network1
  phpmyadmin1:
    container_name: phpmyadmin1
    image: phpmyadmin
    ports:
      - "1500:80"
    environment:
      - PMA_HOST=mysql1
    networks:
      - network1
    depends_on:
      - mysql1
  queue-worker1:
    container_name: queue-worker1
    build: ./docker/php
    command: php artisan queue:work
    volumes:
      - .:/var/www/html
    networks:
      - network1
    depends_on:
      - php1
      - mysql1
